### ISSUE TITLE
Not inserting ammo to turret if rockets in inventory

### ISSUE THREAD

**Issue by moon6969** [folknor/factorio-fill#3]
I think the https://github.com/folknor/factorio-fill/blob/0fb68503cadcd44335a7832b6ef49248ca475245/control.lua#L299 needs to be in the 'if' block above like so:
```
if inserted and inserted > 0 then
    itemStackCache[ammo] = inserted
    fromInv.remove(itemStackCache[ammo])
    break
end
```

**Comment by folknor** [comment]
Hi!

It works for me - which turret and which different ammo types do you have in inventory?

Thanks for the bug report :-)

**Comment by moon6969** [comment]
Trying to insert to "gun-turret"
Inventory has "firearm-magazine", "piercing-rounds-magazine", "uranium-rounds-magazine", "rocket".
In debug I can see it try & fail to insert "rocket" then it breaks out of loop and doesn't try remainder of ammos in ammoCategory.

**Comment by folknor** [comment]
Ah yes my bad, I've already fixed this locally just not released yet. Hopefully I can do so tomorrow!

Thank you!

**Comment by folknor** [comment]
Hi! Would you mind testing the latest release from https://github.com/folknor/factorio-fill/releases/tag/v0.3.1 ?

I've almost completely rewritten it

**Comment by moon6969** [comment]
Thanks - a quick test of turrets and a tank inserted the relevant ammos correctly.

**Comment by folknor** [comment]
Thank you kindly
